### ISSUE TITLE
error while making sd card image.

### ISSUE THREAD

**Issue by sinkingfund** [robseb/socfpgaPlatformGenerator#3]
Hi.
 I am using Ubuntu 18.01 LTS, I cloned "socfpgaPlatformGenerator" in my project folder, and tried to make custom yocto by executing command.

`$python3 socfpgaPlatformGenerator.py `

it displays a error.

```
ERROR: The script was not executed inside the cloned Github folder
       Please clone this script from Github and execute the script
       directly inside the cloned folder!
URL: https://github.com/robseb/socfpgaPlatformGenerator.git
```

even though i cloned it in my project folder, please take a look into it.

**Comment by robseb** [comment]
Hello sinkingfund,
I fixed this problem. Please remove the socfpgaPlatformGenerator folder and clone it again.
Do you know rsyocto? I have a build script that can go a step further with your Quartus Prime project as shown [here](https://github.com/robseb/rsyocto/blob/rsYocto-1.04/doc/guides/7_customVersions.md).
Robin
